server:
  # Maximum parallel count of industrial steam machine
  # Default: 64
  industrialSteamMachineMaxParallels: 64

  # Whether large advanced turbine will blow up entities in front of rotor holder when working
  # Default: true
  enableAdvancedTurbineBlowing: true

