values:
  # The exponent used each time the Omnic Synthesizer performs an operation.
  omnicSynthesizerExponent: 1.557

  # Whether the microminer is returned upon a microverse reaching zero integrity.
  microminerReturnedOnZeroIntegrity: true

  # Force pride month easter eggs regardless of time of year
  forcePrideMonth: false

  # The efficiency multiplier for the Sculk Vat. Would make it this many times less efficient at empty/full compared to half.
  sculkVatEfficiencyMultiplier: 33.0

  # Fluid ID for Liquid XP for the Sculk Vat.
  sculkVatExperienceFluidID: enderio:xp_juice

  # Whether to include the hostile microverse tooltip for the microverse type sensor hatch.
  hostileMicroverseTooltip: false

